# Generated by Django 5.0.4 on 2024-04-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_client_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parkings.parking'),
        ),
    ]
